name: npm-unpublish
on:
  release:
    types: [created]
jobs:
  unpublish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm unpublish yorkie-ui@0.2.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
